version: "3.7"
services:
  db:
    image: influxdb
    restart: always
    environment:
      #- INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_DB=db
      - INFLUXDB_HOST=db
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=jeanpaul
      - INFLUXDB_USER=jeanpaul
      - INFLUXDB_USER_PASSWORD=jeanpaul
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - databasev:/var/lib/influxdb
  mysql:
    image: mysql:5.7
    volumes:
      - mysqlv:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jeanpaul
      MYSQL_DATABASE: ccpiot
      MYSQL_USER: jeanpaul
      MYSQL_PASSWORD: jeanpaul
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  api:
    image: cresus/cloud-computing-api:v3
    command: npm start
    ports:
      - 1337:1337
  dashboard:
    image: grafana/grafana
    ports:
      - 3000:3000
  notebook:
    image: cresus/cloud-computing-notebook:v1
    ports:
      - 8888:8888
    volumes:
      - anacondav:/opt/notebooks
volumes:
  databasev:
  mysqlv:
  apiv:
  anacondav:
  dashboardv: