version: "3.7"
services:
  db:
    build: ./influx/
    container_name: cloud-computing-influxdb
    image: cresus/cloud-computing-influxdb
    restart: always
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - databasev:/var/lib/influxdb
  influxdb_cli:
    links:
      - db
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: cloud-computing-influxcli
    entrypoint: influx setup --bucket smart_farm -t SSDZ8-RZvXcNrX_Tqo7dfWED0fALu_1LZB2iSLSpsHncLyEmDro4sBgp7l6bMTpcfHxQv87y2Gm_axoLOYC2bg== -o jeanpaultech --username=admin --password=jeanpaul --host=http://db:8086 -f
    restart: on-failure:10
    depends_on:
      - db
  dashboard:
    build: ./grafana/
    container_name: cloud-computing-grafana
    image: cresus/cloud-computing-grafana
    ports:
      - 3000:3000
    volumes:
      - dashboardv:/var/lib/grafana
  api:
    build: ./api/
    container_name: cloud-computing-api
    image: cresus/cloud-computing-api
    command: npm start
    volumes:
      - apiv:/usr/src/app
    ports:
      - 1337:1337
  notebook:
    build: ./notebook/
    container_name: cloud-computing-notebook
    image: cresus/cloud-computing-notebook
    ports:
      - 8888:8888
    volumes:
      - anacondav:/opt/notebooks
volumes:
  databasev:
  mysqlv:
  apiv:
  anacondav:
  dashboardv:
